[package]
name = "migration-scheduler"
version = "0.2.3"
edition = "2024"

[lib]
name = "migration_scheduler"
path = "src/lib.rs"

[[bin]]
name = "migration-scheduler"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
axum = { version = "0.8", features = ["macros"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "fs", "trace"] }
uuid = { version = "1.21.0", features = ["v4", "serde"] }
sha2 = "0.11.0-rc.5"
chrono = { version = "0.4", features = ["serde"] }


include_dir = { version = "0.7", features = ["glob"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
yougile-api-client = { git = "https://github.com/kexan/yougile-rs.git", branch = "main" }
fastrand = "2.3.0"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["cors"] }
axum = "0.8"

[[test]]
name = "api_test"
path = "tests/api_test.rs"
