name: Build release binary

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Install Rust
        uses: actions-rs/toolchain@master
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v5.0.3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v6.0.0
        with:
          name: release-binary
          path: target/release/YOUR_BINARY_NAME
